# Generated by Django 4.2.4 on 2023-10-18 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_student_student_class_alter_teacher_department'),
        ('alumnus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='accounts.student'),
        ),
        migrations.AlterField(
            model_name='resultsheet',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='accounts.student'),
        ),
        migrations.AlterField(
            model_name='resultsheet',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultsheets', to='alumnus.subject'),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scholarships', to='accounts.student'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='accounts.class'),
        ),
    ]
