# Generated by Django 4.2.4 on 2023-10-22 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnus', '0003_remove_job_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarship',
            name='degree',
            field=models.CharField(choices=[('BACHELOR', 'Bachelor'), ('MASTER', 'Master'), ('PHD', 'PHD')], default='MASTER', max_length=50),
        ),
    ]
