# Generated by Django 4.2.4 on 2023-11-08 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_admin_faculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='is_graduated',
            field=models.BooleanField(default=False),
        ),
    ]
