# Generated by Django 4.2.4 on 2023-11-09 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_class_is_graduated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='name',
            field=models.CharField(default='no-name', max_length=150),
        ),
    ]
