# Generated by Django 4.2.4 on 2023-09-25 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuperAdminNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('attachment', models.FileField(blank=True, upload_to='notice/%Y/%m/%d')),
                ('registry_date', models.DateField(auto_now_add=True)),
                ('audience', models.CharField(choices=[('STUDENT', 'Student'), ('TEACHER', 'Teacher'), ('ALUMNUS', 'Alumnus'), ('STAFF', 'Staff')], max_length=20)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.superadmin')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AdminNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('attachment', models.FileField(blank=True, upload_to='notice/%Y/%m/%d')),
                ('registry_date', models.DateField(auto_now_add=True)),
                ('audience', models.CharField(choices=[('TEACHER', 'Teacher'), ('STUDENT', 'Student'), ('ALUMNUS', 'Alumnus')], max_length=20)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.admin')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
