# Generated by Django 4.2.4 on 2023-10-18 01:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('attachment', models.FileField(blank=True, upload_to='notice/%Y/%m/%d')),
                ('registry_date', models.DateField(auto_now_add=True)),
                ('audience', models.CharField(choices=[('STUDENT', 'Student'), ('TEACHER', 'Teacher'), ('ALUMNUS', 'Alumnus'), ('STAFF', 'Staff'), ('ALL', 'All')], max_length=20)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='superadminnotice',
            name='author',
        ),
        migrations.DeleteModel(
            name='AdminNotice',
        ),
        migrations.DeleteModel(
            name='SuperAdminNotice',
        ),
    ]
