# Generated by Django 4.2.4 on 2023-10-19 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_student_student_class_alter_teacher_department'),
        ('notice', '0002_notice_remove_superadminnotice_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='faculty',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.faculty'),
        ),
    ]
