# Generated by Django 4.2.4 on 2023-10-21 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_student_student_class_alter_teacher_department'),
        ('notice', '0004_alter_notice_faculty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.faculty'),
        ),
    ]
