# Generated by Django 4.2.4 on 2023-10-22 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0005_alter_notice_faculty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='registry_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
