# Generated by Django 4.2.4 on 2023-10-17 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
