# Generated by Django 4.2.4 on 2023-10-17 17:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('complaints', '0002_complaint_private'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='student',
        ),
        migrations.AddField(
            model_name='complaint',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complaint', to=settings.AUTH_USER_MODEL),
        ),
    ]
